config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "userRestaurants", to: "pages#userRestaurants"
  get "userRatings", to: "pages#userRatings"
  get "userComments", to: "pages#userComments"
  get "userFavorites", to: "pages#userFavorites"
  get "userProfile", to: "pages#userProfile"

  resources :restaurants do
    resources :favorites, only: :create
    resources :meals, only: [ :new, :create, :edit, :update] do
      resources :ingredients, only: [ :new, :create, :edit, :update]
    end
    resources :comments, only: [:new, :create]
    resources :ratingrs, only: [:new, :create]
  end

  resources :meals, only: [:show, :destroy]
  resources :ingredients, only: [:show, :destroy]
  resources :comments, only: :destroy
  resources :favorites, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="homepage">
    <div>
        <h2 class = "title">Best rated restaurants</h2>
    </div>
    
    <div class="display-card-and-btn" data-controller="defilement-card">
        <button class="left" data-action="click->defilement-card#previous">
            <i class="fa-sharp fa-solid fa-circle-chevron-left"></i>
        </button>
        <div class="display-items" data-defilement-card-target="cards" >
            <% @bestRestaurants.each do |restaurant| %>
                <%= render "components/smallcard", restaurant: restaurant %>
            <% end %>
        </div>
        <button class="right" data-action="click->defilement-card#next">
            <i class="fa-sharp fa-solid fa-circle-chevron-right"></i>
        </button>
    </div>
    
        
    
    
    <div>
        <h2 class = "title">Last open restaurants</h2>
    </div>

    <div class="display-card-and-btn" data-controller="defilement-card">
        <button class="left" data-action="click->defilement-card#previous">
            <i class="fa-sharp fa-solid fa-circle-chevron-left"></i>
        </button>
        <div class="display-items" data-defilement-card-target="cards" >
            <% @newerRestaurants.each do |restaurant| %>
                <%= render "components/smallcard", restaurant: restaurant %>
            <% end %>
        </div>
        <button class="right" data-action="click->defilement-card#next">
            <i class="fa-sharp fa-solid fa-circle-chevron-right"></i>
        </button>
    </div>
    
    <div>
        <h2 class = "title">The most comments restaurants</h2>
    </div>

    <div class="display-card-and-btn" data-controller="defilement-card">
        <button class="left" data-action="click->defilement-card#previous">
            <i class="fa-sharp fa-solid fa-circle-chevron-left"></i>
        </button>
        <div class="display-items" data-defilement-card-target="cards" >
            <% @popularRestaurants.each do |restaurant| %>
                <%= render "components/smallcard", restaurant: restaurant %>
            <% end %>
        </div>
        <button class="right" data-action="click->defilement-card#next">
            <i class="fa-sharp fa-solid fa-circle-chevron-right"></i>
        </button>
    </div>

    <div class="commentmeal">

        <div class="commentside">
            <h2>The last comments</h2>
            <% @lastComments.each do |comment| %>
                <%= render "components/commentcardhome", comment: comment %>
            <% end %>
        </div>
        

        <div class="mealside">
            <h2>The last new meals</h2>
            <% @lastMeals.each do |meal| %>
                <%= link_to meal_path(meal) do %>
                    <%= render "components/cardproduct", meal: meal %>
                <% end %>
            <% end %>
        </div>
        
    </div>
    
</div>

app/views/pages/userComments.html.erb
<div class="comments">

    <div class="title-line">
        <div class="line">
        </div>
        <h2>All your comments</h2>
        <div class="line">
        </div>
    </div> 

    <div class="list-comments">
        <% @comments.each do |comment| %>
            <%= link_to restaurant_path(comment.restaurant), title: "Click to show the restaurant" do %>
                <div class="restaurant">
                    <%= comment.restaurant.name %>
                </div>
                <%= render "components/commentcardhome", comment: comment %>
            <% end %>
        <% end %>
    </div>

</div>

app/views/pages/userFavorites.html.erb
<div class="user-restaurant">

    <div class="title-line">
        <div class="line">
        </div>
        <h2>All your favories</h2>
        <div class="line">
        </div>
    </div> 

    <div class="list-restaurants">
        <% if @favorites.empty? %>
            <p id="list-empty">You don't have any favorite yet.</p>
        <% else %>
            <% @favorites.each do |favorite| %>
                <%= link_to restaurant_path(favorite.restaurant), title: "Click to show the restaurant" do %>
                    <%= render "components/cardrestaurant", restaurant: favorite.restaurant %>
                <% end %>
            <% end %>
        <% end %>
    </div>  
</div>

app/views/pages/userProfile.html.erb
<div class="user-profile">
    <div class="space-between"></div>

    <div class="img-username">

        <div class="outside-user-img">
            <% if current_user.photo.key.nil? %>
                <div class="user-img" style="background-image: url('<%= image_path "LogoHuntingFoodWithBg.jpg" %>'); background-size: cover; background-position: center;">
                </div>
            <% else %>
                <div class="user-img" style="background-image: url('<%= cl_image_path current_user.photo.key %>'); background-size: cover; background-position: center;">
                </div>
            <% end %>
        </div>

        <div class="info-user">
            <h3><%= current_user.nickname %></h3>
        </div>

    </div>

    <div class="space-between"></div>
    <div class="show-info-user">
        <p>You created your account the <%= current_user.created_at.strftime("%A %-d %B %Y")  %>.</p>
        <p>You have been with us for <%= formatted_duration(Time.current - current_user.created_at) %>.</p>
        <p>You have <%= current_user.restaurants.count %> restaurant(s).</p>
        <p>You have <%= current_user.favorites.count %> favorite(s).</p>
    </div>

    <div class="space-between"></div>

    <div class="show-user-link">
        <p><%= link_to "Edit your profile", edit_user_registration_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
        <p><%= link_to "Delete your profile", user_registration_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
    </div>
    

</div>

app/views/pages/userRatings.html.erb
<div class="user-restaurant">

    <div class="title-line">
        <div class="line">
        </div>
        <h2>All your raitings</h2>
        <div class="line">
        </div>
    </div> 

    <div class="list-restaurants">
        <% @ratingrs.each do |ratingr| %>
            <%= link_to restaurant_path(ratingr.restaurant), title: "Click to show the restaurant" do %>
                <%= render "components/cardrestaurant", restaurant: ratingr.restaurant %>
            <% end %>
            <div class="raiting-absolute">
                <div class="raiting">
                    <p><%= ratingr.content %>/5</p>
                </div>
            </div>
            
        <% end %>
    </div>  
</div>

app/views/pages/userRestaurants.html.erb
<div class="user-restaurant">

    <div class="title-line">
        <div class="line">
        </div>
        <h2>All your restaurants</h2>
        <div class="line">
        </div>
    </div> 

    <div class="list-restaurants">
        <% @restaurants.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant), title: "Click to show the restaurant" do %>
                <%= render "components/cardrestaurant", restaurant: restaurant %>
            <% end %>
        <% end %>
    </div>  
</div>