config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "userRestaurants", to: "pages#userRestaurants"
  get "userRatings", to: "pages#userRatings"
  get "userComments", to: "pages#userComments"
  get "userFavorites", to: "pages#userFavorites"
  get "userProfile", to: "pages#userProfile"

  resources :restaurants do
    resources :favorites, only: :create
    resources :meals, only: [ :new, :create, :edit, :update] do
      resources :ingredients, only: [ :new, :create, :edit, :update]
    end
    resources :comments, only: [:new, :create]
    resources :ratingrs, only: [:new, :create]
  end

  resources :meals, only: [:show, :destroy]
  resources :ingredients, only: [:show, :destroy]
  resources :comments, only: :destroy
  resources :favorites, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meal.rb
class Meal < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  
  belongs_to :restaurant
  has_many :ingredients, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
    before_action :set_restaurant, only: [:new, :create, :edit, :update]
    skip_before_action :authenticate_user!, only: :show

    def new
        # @restaurant = Restaurant.find(params[:restaurant_id])
        @meal = Meal.new
        @meal.restaurant = @restaurant
        authorize @meal
    end

    def create
        @meal = Meal.new(meal_params)
        # @restaurant = Restaurant.find(params[:restaurant_id])
        @meal.restaurant = @restaurant
        @meal.address = @restaurant.address
        @meal.protein = 0
        @meal.carbohydrate = 0
        @meal.fat = 0
        authorize @meal
        if @meal.save
            # authorize @meal
            redirect_to restaurant_path(@restaurant)
        else
            render :new
        end
        # authorize @meal
    end

    def show
        @meal = Meal.find(params[:id])
        authorize @meal
        @ingredients = Ingredient.where(meal_id: @meal)
        # raise
    end

    def edit
        # @restaurant = Restaurant.find(params[:restaurant_id])
        @meal = Meal.find(params[:id])
        authorize @meal
        # @restaurant = Restaurant.find(@meal.restaurant_id)
    end

    def update
        @meal = Meal.find(params[:id])
        authorize @meal
        if @meal.update(meal_params)
            # @restaurant = Restaurant.find(params[:restaurant_id])
            redirect_to restaurant_path(@restaurant)
        else
            render :edit
        end
    end

    def destroy
        @meal = Meal.find(params[:id])
        authorize @meal
        @meal.destroy
        redirect_to restaurant_path(@meal.restaurant_id)
    end

private

    def set_restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def meal_params
        params.require(:meal).permit(:name, :price, :description, :photo)
    end

end

app/views/meals/_form.html.erb
<div class="form-meal">

  <h2>Your meal's details</h2>

  <div class="info">
  
    <%= simple_form_for [ @restaurant, @meal ] do |f| %>
      <%= f.input :name, label: false, placeholder: 'Name' %>
      <%= f.input :description, label: false, placeholder: 'Description' %>
      <%= f.input :price, label: false, placeholder: 'Price' %>
      <%= f.input :photo, label: "Upload some pictures", as: :file %>

      <div class="submit-back">
          <%= f.submit "Create your meal" %>
      </div>
    <% end %>
  
      <%= link_to "Back", :back %>
  </div> 
  
</div>

app/views/meals/_info_window_meal.html.erb
<h2><%= meal.name %></h2>
<p><%= meal.address %></p>
<p><%= meal.price %></p>

app/views/meals/edit.html.erb
<%= render "form", meal: @meal %>

app/views/meals/new.html.erb
<%= render "form", meal: @meal %>

app/views/meals/show.html.erb
<div class="show-meal">
    <% if @meal.photo.attached? %>
            
        <div class="img-meal">

            <%= cl_image_tag @meal.photo.key, :crop => "crop" %>
<%# , :gravity=>"auto" %>
        </div>

    <% else %>

        <div class="img-meal">

            <%= image_tag 'LogoHuntingFoodWithBg', crop: :fill %>

        </div>
        
    <% end %>
   
    <div class="meal-ingredient" data-controller="defilement-ingredient-show"
    data-defilement-ingredient-show-ningredients-value = <%= @meal.ingredients.count %> >

        <div class="info-meal">
      
            <div class="name">

                <h2> <%= @meal.name %> </h2>

            </div>
            

            <div class="description">
                <p><%= @meal.description %> </p>

                <p>Price: <%= @meal.price %>$</p>
            </div>

            <div class="nutriments">

                <p>Proteins: <%= (@meal.protein % 1) == 0 ? @meal.protein.to_i : @meal.protein %>g </p>
                <p>Carbohydrates: <%= (@meal.carbohydrate % 1) == 0 ? @meal.carbohydrate.to_i : @meal.carbohydrate %>g </p>
                <p>Fat: <%= (@meal.fat % 1) == 0 ? @meal.fat.to_i : @meal.fat.round %>g </p>

            </div>

            <%= link_to restaurant_path(@meal.restaurant), title: "Click on it to access to the restaurant" do %>
                <div class="restaurant">

                    <div class="name-rating">

                        <h2>From <%= @meal.restaurant.name %> </h2>

                        <div class="rating-restaurant">
                        <% if @meal.restaurant.rating == 0 %>
                            <p>?</p>
                        <% else %>
                            <%= (@meal.restaurant.rating % 1) == 0 ? @meal.restaurant.rating.to_i : @meal.restaurant.rating %>
                        <% end %>
                        </div>
                        
                    </div>

                    <div class="address-phone">

                        <p><%= @meal.restaurant.address %> </p>
                        <p><i class="fa-solid fa-phone"></i> <%= @meal.restaurant.phone %> </p>

                        <% if @meal.restaurant.open? %>
                            <p class="open"><span>Open</span>. It will close in <%= @meal.restaurant.whenClose  %></p> 
                        <% else %>
                            <p class="closed"><span>Closed</span>. It will open in <%= @meal.restaurant.whenOpen  %></p>
                        <% end %>
                    </div>
                
                </div>

            <% end %>

            <% if @meal.restaurant.user == current_user %>
                <div class="setting">
                    <p>
                        <%= link_to edit_restaurant_meal_path(@meal.restaurant, @meal), title: "Edit your meal" do %>
                            <i class="fa-solid fa-pen-to-square"></i>
                        <% end %>    
                    </p>
                    <p>
                        <%= link_to new_restaurant_meal_ingredient_path(@meal.restaurant, @meal), title: "Add a ingredient to the meal" do %>
                            <i class="fa-solid fa-cart-plus"></i>
                        <% end %>                    
                    </p>   
                    <p>
                        <%= link_to meal_path(@meal), method: :delete, data: { confirm: "Are you sure?" }, title: "Delete your meal" do %>
                            <i class="fa-solid fa-trash"></i>
                        <% end %>
                    </p> 
                </div>
            <% end %>


        </div>

        <div class="ingredients" > 
            <div class="title-line">
                <div class="line">
                </div>
                <h2>Ingredients</h2>
                <div class="line">
                </div>
            </div>


            <button class="btn-top" data-action="click->defilement-ingredient-show#up">
                <i class="fa-solid fa-circle-chevron-up"></i>
            </button>
        
            
            <div class="list-ingredients" data-defilement-ingredient-show-target = "cards">
            

                <% if @ingredients.nil? %>
                    <p>No ingredient added yet.</p>
                <% else %>
                    <% @ingredients.each do |ingredient| %>

                        <%= render "components/cardIngredient", ingredient: ingredient %>

                    <% end %>
                <% end %>

            </div>

            <button class="btn-bottom" data-action="click->defilement-ingredient-show#down">
                <i class="fa-solid fa-circle-chevron-down"></i>
            </button>
            
        </div>
    </div>



    </div>
</div>